apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c7xn1u82d-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c7xn1u82d-go 
  name: c7xn1u82d-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c7xn1u82d-go 
